services:
  auctionsdb:
    image: postgres

  mongodb:
    image: mongo

  messagebroker:
    image: rabbitmq:3-management-alpine

  auctions.api:
    image: ${DOCKER_REGISTRY-}auctionsapi
    build:
      context: .
      dockerfile: src/Services/Auctions/Auctions.API/Dockerfile

volumes:
  postgresdata:
  mongodata: