services:
  postgresdb:
    image: postgres

  mongodb:
    image: mongo

  messagebroker:
    image: rabbitmq:4-management-alpine

  auctions.api:
    # image: <unique_name>/auction-srv:latest 
    image: ${DOCKER_REGISTRY-}auctionsapi
    build:
      context: .
      dockerfile: src/Services/Auctions/Auctions.API/Dockerfile

  search.api:
    image: ${DOCKER_REGISTRY-}searchapi
    build:
      context: .
      dockerfile: src/Services/Search/Search.API/Dockerfile

  bidding.api:
    image: ${DOCKER_REGISTRY-}biddingapi
    build:
      context: .
      dockerfile: src/Services/Bidding/Bidding.API/Dockerfile

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityService/Dockerfile

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: src/Services/ApiGateway/ApiGateway/Dockerfile

  notifications.api:
    image: ${DOCKER_REGISTRY-}notificationsapi
    build:
      context: .
      dockerfile: src/Services/Notifications/Notifications.API/Dockerfile

volumes:
  postgresdata:
  mongodata:




